### ISSUE TITLE
production

### ISSUE THREAD

**Issue by siddo420** [pwnall/w3gram-server#1]
can I use it in production?

do I have to use Heroku? Can't I host myself on a node server?

**Comment by pwnall** [comment]
@siddo420 Sorry, I didn't see this until now.

It's probably too late, but... I used it on Heroku and it seems to work fine. So production use seems ok.

The code doesn't depend on any Heroku magic, so you should be able to use it on your own server. You'll need to set up a Postgres database as described in the dev instructions.
